name: CI - apigateway 

on:
  push:
    branches:
      - main
      - release/*
      - develop
    paths: 'apigateway/**'
  pull_request:
    branches:
      - main
      - release/*
      - develop
    paths:
      - 'apigateway/**'

jobs:
  build-apigateway:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apigateway
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant permission
      run: chmod +x ./gradlew
    
    - name: Build
      run: ./gradlew build
