name: CI for React

on:
  push:
    branches:
      - main
      - release/*
      - develop
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - release/*
      - develop
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test -- --watchAll=false
        
      - name: Build React app
        run: CI=false npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
          retention-days: 30
      
      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run:  |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          docker build -t ${{secrets.DOCKER_USERNAME}}/my-react-app:$SHORT_SHA .
          docker tag ${{secrets.DOCKER_USERNAME}}/my-react-app:$SHORT_SHA ${{secrets.DOCKER_USERNAME}}/my-react-app:latest      
      - name: Push to Docker Registry
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          docker push ${{secrets.DOCKER_USERNAME}}/my-react-app:$SHORT_SHA
          docker push ${{secrets.DOCKER_USERNAME}}/my-react-app:latest
      - name: Comment on success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `✅ **React CI Passed!**
        
            🎉 All tests are passing
            📊 Build completed successfully
            🚀 Ready for deployment`
            });
      - name: Comment on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `❌ **React CI Failed**
        
            ⚠️ Some tests are failing
            🔍 Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            🛠️ Fix the issues and push again`
            });
        
