name: CI for React

on:
  phsh:
    paths:
      - 'untitled/**'
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: untitled
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test -- --watchAll=false
        
      - name: Build React app
        run: npm run build
        
