name: CI - User Service

on:
  push:
    paths: 'user-service/**'
  pull_request:
    paths:
      - 'user-service/**'

jobs:
  build-user-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user-service
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant permission
      run: chmod +x ./gradlew
    
    - name: Build
      run: ./gradlew build
